### ISSUE TITLE
Invite the committer in a new issue rather than in a PR comment

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/commitbit#4]
@mattwynne you suggested in a conversation that you'd rather have a separate ticket created to onboard new committers. Like you were doing in the script I removed in https://github.com/cucumber/cucumber-ruby/commit/f998a8b03b55df062aa874c32d526acd170e3c5f

I'm all for it if someone takes the time to implement it. I'd like to preserve the existing behaviour and have an env var choose between the two strategies.

What repo should the ticket be created in? Could be a single repo (cucumber/cucumber) or it could be the same repo as the PR was against. Again, could be configurable with an env var.

**Comment by muggenhor** [comment]
Additionally I think the invitation message should be changed to very clearly indicate it is automated.

**Comment by mattwynne** [comment]
@aslakhellesoy perhaps you could make yourself available to pair with someone else in the community who'd like to learn more about serverless? It would be a good way to grow the number of people who know this code.

TBH I think that rather than using environment variables we should just have one consistent strategy throughout the org. I'd continue to make the case that having one issue per new member adds a bit more ceremony / celebration around it. A single comment by a bot somewhere in a PR is harder to see. If there's only one committer team, then I guess it makes sense to create the ticket on the cucumber/cucumber monorepo. That way more people will be notified and can post welcoming comments on the ticket!

**Comment by aslakhellesoy** [comment]
I think conversations about commitbit in GitHub, mailing lists and Slack are sufficient @mattwynne. 

[Serverless Framework](https://serverless.com/) and [AWS Lambda](https://aws.amazon.com/lambda) are interesting technologies, but I'm not going to prioritise educating people in the Cucumber community about them. I've got many other things I want/need to do that has higher priority. The Serverless docs are excellent - that's how I picked it up.

This is a tiny service - there's not much to it - it's all in handler.js. You seem to care about the bot creating issues. Do you care enough to send a PR? ;-)

**Comment by mattwynne** [comment]
TBH I don't care that much about this particular feature, no 😄
